version: "2.0"
services:
    bitbucket_app:
        image: threatworx/bitbucket_app_server:latest
        container_name: threatworx_bitbucket_app
        ports:
            - 443:443
        volumes:
            - ./config:/opt/tw_bitbucket_app/config
        restart: on-failure:2
    watchtower:
        image: containrrr/watchtower
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
        command: --interval 86400 --cleanup --remove-volumes --debug threatworx_bitbucket_app
        depends_on: 
            - bitbucket_app
